// playgrounds/vue/src/App.vue
<script setup lang="ts">
import { ref } from "vue";

const count = ref(0);
</script>

<template>
  <main>
    <h1>Tooltify Vue Playground</h1>
    <button @click="count++">Count is {{ count }}</button>
  </main>
</template>

<style scoped>
main {
  font-family: system-ui, sans-serif;
  padding: 2rem;
}
</style>

// playground/src/App.tsx
import { useState } from "react";
import { Button } from "./components/Button";

function Counter() {
  const [count, setCount] = useState(0);
  return (
    <button onClick={() => setCount(count + 1)}>
      count: {count}
    </button>
  );
}

export default function App() {
  return (
    <div>
      <h1>Tooltify Playground</h1>
      <Counter />
      <Button />
    </div>
  );
}
